services:
  - type: web
    name: agricode
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production 